config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  post '/home/guest_sign_in', to: 'static_pages#new_guest'
  devise_for :users
  resources :chores do
    resources :chore_records, only: [:new, :edit]
  end
  resources :chore_records, only: [:create, :update, :destroy]
  resources :profiles do
    member do
      post :select
    end
  end
  resources :rewords do
    member do
      post :exchange
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord

  # -- [Association] --
  belongs_to :user
  has_many :points, dependent: :destroy
  has_many :chore_records, dependent: :destroy

  # -- [validation] --
  validates :name, presence: true, length: { maximum: 30 }


  # 所持ポイント
  def point
    self.points.sum(:point)
  end
  # 累計獲得ポイント
  def total_point
    self.points.where(event: Point.events[:chore_record]).sum(:point)
  end
  # お手伝い件数
  def chores_count
    self.chore_records.count
  end
  # ポイント交換件数
  def rewords_count
    self.points.where(event: Point.events[:reward_exchange]).count
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show,:select, :edit, :update, :destroy]

  def index
    @profiles = current_user.profiles
    unless @profiles.present?
      flash[:notice] = "プロフィールを新規登録してください。"
      redirect_to new_profile_url
    end
  end

  def show
    
  end

  def select
    # 挨拶
    unless current_profile&.id == @profile.id
      flash[:notice] = greeting @profile.name
    end

    # 現在のプロフィールを破棄
    forget_profile unless selected_profile?
    # 選択されたプロフィール情報をセッションに保存
    remember_profile(@profile)

    redirect_to root_path
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    if @profile.save
      flash[:success] = "「#{@profile.name}」のプロフィールを登録しました。"
      redirect_to profiles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      flash[:success] = "「#{@profile.name}」のプロフィールを更新しました。"
      redirect_to profiles_path
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    flash[:success] = "「#{@profile.name}」のプロフィールを削除しました。"
    redirect_to profiles_path
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :admin)
  end

  # 対象idのお手伝い情報を設定
  def set_profile
    @profile = current_user.profiles.find(params[:id])
  end

  # 挨拶
  def greeting(name)
    hour = Time.zone.now.hour
    if hour.between?(5, 11)
      "おはようございます、#{name} さん"
    elsif hour.between?(12, 16)
      "こんにちは、#{name} さん"
    elsif hour.between?(0, 4) || hour.between?(17, 24)
      "こんばんは、#{name} さん"
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

  # プロフィールIDを記憶する
  def remember_profile(profile)
    session[:profile_id] = profile.id
  end

  # プロフィールIDを破棄する
  def forget_profile
    session.delete(:profile_id)
  end

  # session に対応するプロフィールを返す
  def current_profile
    if (profile_id = session[:profile_id])
      @current_profile ||= Profile.find_by(id: profile_id)
    end
  end

  # プロフィール選択状態の確認
  def selected_profile?
    !current_profile.nil?
  end

end

app/views/profiles/_form.html.slim
= form_with model: @profile, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :admin, class: 'checkbox' do
      = f.check_box :admin, class: 'form-check-input'
      span= Profile.human_attribute_name(:admin)

  = f.submit nil, class: 'btn btn-info btn-block mt-3'

app/views/profiles/edit.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.col-md-8.offset-md-2
  = render 'form'

  hr.mt-5
  = link_to "削除", profile_path(@profile),
  data: {confirm: "ポイントが全て失われます。よろしいですか？"},method: :delete, class: 'btn btn-danger btn-block'

app/views/profiles/index.html.slim
- provide(:title, t('.title'))
h1= t('.title')
h2 どなたが利用しますか？

.col-md-8.offset-md-2
  .row.flex-wrap
    - @profiles.each do |p|
      .col-6.col-md-4
        = link_to p.name, select_profile_path(p), method: :post, class: 'btn btn-outline-info profile-box'
        .mt-1.mb-3.text-center
          = link_to edit_profile_path(p) do
            = fa_icon 'edit' 
            = " 編集"
    .col-6.col-md-4
      = link_to "+", new_profile_path, class: 'btn btn-secondary profile-plus-box'

app/views/profiles/new.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.col-md-8.offset-md-2
  = render 'form'

  

app/views/profiles/show.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.row
  .col-md-4
    = render 'shared/profile', profile: @profile

    .mb-3
    = render 'shared/profile_rewords', point_rewords: @profile.points.reward.recent

  .mb-3
  .col-md-8
    .card
      .card-header お手伝いの総合記録
      .card-body
        table.table.table-hover
          tbody
            tr
              td お手伝いを開始した日
              td.text-right= l(@profile.created_at, format: :ymd)
            tr
              td お手伝いをした回数
              td.text-right= "#{@profile.chores_count.to_s(:delimited)} 回"
            tr
              td 累計獲得ポイント数
              td.text-right= "#{@profile.total_point.to_s(:delimited)} pt"
            tr
              td ポイント交換した数
              td.text-right= "#{@profile.rewords_count.to_s(:delimited)} 個"

        / = link_to "#" do
        /   = fa_icon 'plus-circle 2x'
      
    .mb-3
    .card
      .card-header 履歴
      .card-body style="overflow-x: hidden; overflow-y: scroll; height: 400px;"
        table.table.table-hover
          thead.thead-default
            tr
              th style="width: 20%;"= Point.human_attribute_name(:event)
              th style="width: 30%;"= "名称"
              th style="width: 20%;"= Point.human_attribute_name(:point)
              th style="width: 30%;"= Point.human_attribute_name(:created_at)
          tbody
            - @profile.points.recent.each do |point|
              tr
                td= Point.events_i18n[Point.events.key(point.event)]
                td
                  - if Point.events.slice(:chore_record, :chore_cancel).values.include?(point.event)
                    = link_to point.chore do
                      = fa_icon 'calendar-o', class: 'icon_chores_list'
                      span.ml-2= point.chore&.name
                  - if point.event == Point.events[:reward_exchange]
                    = point.reword.name
                td.text-right.td-point
                  = (point.point.positive? ? "+": "") + "#{point.point.to_s(:delimited)} pt"
                td.center.small
                  = l(point.created_at, format: :long)
                td.center