config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  post '/home/guest_sign_in', to: 'static_pages#new_guest'
  devise_for :users
  resources :chores do
    resources :chore_records, only: [:new, :edit]
  end
  resources :chore_records, only: [:create, :update, :destroy]
  resources :profiles do
    member do
      post :select
    end
  end
  resources :rewords do
    member do
      post :exchange
    end
  end
end

app/models/reword.rb
class Reword < ApplicationRecord

  # -- [Association] --
  has_many :points
  
  # -- [validation] --
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 255 }
  validates :cost_point, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  # -- [scope] --
  # 最新を取得
  scope :maxcost, -> { order(cost_point: :desc)}
end

app/controllers/rewords_controller.rb
class RewordsController < ApplicationController
  before_action :authenticate_user!         # ログインユーザーのみアクセス許可
  before_action :confirm_selected_profile   # プロフィール選択中のみアクセス許可
  before_action :set_reword, only: [:edit, :update, :destroy, :exchange]

  def index
    @rewords = current_user.rewords.maxcost
  end

  def new
    @reword = Reword.new
  end

  def create
    @reword = current_user.rewords.new(reword_params)
    if @reword.save
      flash[:success] = "「#{@reword.name}」の商品情報を登録しました。"
      respond_to do |format|
        format.html { redirect_to rewords_path }
        format.js
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @reword.update_attributes(reword_params)
      flash[:success] = "「#{@reword.name}」の商品情報を更新しました。"
      redirect_to rewords_path
    else
      render :edit
    end
  end

  def destroy
    @reword.destroy

    respond_to do |format|
      format.html { redirect_to rewords_path }
      format.js
    end
  end

  def exchange
    @point = current_profile.points
                  .build(point: -@reword.cost_point,
                        event: Point.events[:reward_exchange],
                        reword: @reword)
    if @point.save
      @rewords = current_user.rewords.maxcost
      respond_to do |format|
        format.html { redirect_to rewords_path, flash: {success: "「#{@reword.name}」とポイント交換しました。"} }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to rewords_path, flash: {danger: "「#{@reword.name}」とポイントを交換できませんでした。"} }
        format.js
      end
    end
  end

  private

  def reword_params
    params.require(:reword).permit(:name, :description, :cost_point, :asin)
  end

  def set_reword
    @reword = current_user.rewords.find(params[:id])
  end
end

app/helpers/rewords_helper.rb
module RewordsHelper
end

app/views/rewords/_exchange_modal.html.slim
- rewords.each do |reword|
  .modal.fade[tabindex="-1" role="dialog" aria-labelledby="exchangeModalLabel-#{reword.id}" aria-hidden="true" id="exchangeModal-#{reword.id}"]
    .modal-dialog[role="document"]
      .modal-content
        .modal-header
          h5.modal-title id="exchangeModalLabel-#{reword.id}"
            = "【ポイント交換】"
          button.close[type="button" data-dismiss="modal" aria-label="Close"]
            span[aria-hidden="true"]
              | ×
        
        .modal-body
          p 選択した商品と交換しますか？
          
          h1.mb-5= "#{reword.name}"
          
          table.table
            tbody
              tr
                th.text-left style="width: 35%;"
                  = Reword.human_attribute_name(:cost_point)
                td.text-right style="width: 65%;"
                  = "#{reword.cost_point.to_s(:delimited)} pt"
              tr
                th.text-left 所持ポイント
                td.text-right
                  - after_point = current_profile.point - reword.cost_point
                  = "#{current_profile.point.to_s(:delimited)} pt　→　"
                  = content_tag :span, "#{after_point.to_s(:delimited)} pt", 
                  class: (after_point < 0 ? "text-danger" : "")
          = content_tag :div, "ポイントが不足しています", class: "text-right text-danger" if after_point < 0
        .modal-footer
          button.btn.btn-secondary[type="button" data-dismiss="modal"]
            | 閉じる
          - if after_point >= 0
            = link_to "交換", exchange_reword_path(reword), method: :post, remote: true, class: 'btn btn-info'
          - else
            button.btn.btn-info[disabled=true]
              | 交換

app/views/rewords/_form.html.slim
= form_with model: @reword, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, required: true, maxlength: 30, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 3, maxlength: 255, class: 'form-control'
  .form-group
    = f.label :cost_point
    .form-inline
      = f.number_field :cost_point, required: true, min: 0, class: 'form-control'
      label.ml-3 pt
  / .form-group
  /   = f.label :asin
  /   = f.text_field :asin, class: 'form-control'

  = f.submit nil, class: 'btn btn-info btn-block'

app/views/rewords/destroy.js.erb
document.querySelector('#reword-<%= @reword.id%>').style.display = 'none';

app/views/rewords/edit.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.col-md-8.offset-md-2
  = render 'form'

app/views/rewords/exchange.js.erb
var min = parseInt( $("#profile_point").text().replace(',','') );
$({count: min}).animate({count: <%= current_profile.point %>}, {
	duration: 1000,
	easing: 'linear',
	progress: function() { 
	    $('#profile_point').html(separate(Math.ceil(this.count)) + " pt"); 
	}
});
$(".profile_rewords").html("<%= escape_javascript(render 'shared/profile_rewords', point_rewords: current_profile.points.reward.recent) %>");
$(".exchangeModal").html("<%= escape_javascript(render 'exchange_modal', rewords: @rewords) %>");

$("#exchangeModal-<%= @reword.id %>").modal('hide');
$('div.modal-backdrop').remove();
$('body').removeClass('modal-open')

app/views/rewords/index.html.slim
- provide(:title, t('.title'))
h1= t('.title')


.row
  .col-md-4
    = render 'shared/profile', profile: current_profile
    .mt-3.profile_rewords
      = render 'shared/profile_rewords', point_rewords: current_profile.points.reward.recent
  .col-md-8
    .card.my-3
      .card-header 商品リスト
      .card-body.pt-0.px-2
        table.table.table-hover
          thead.thead-default
            tr
              th style="width: 25%;"= Reword.human_attribute_name(:name)
              th style="width: 30%;"= Reword.human_attribute_name(:description)
              th style="width: 20%;"= Reword.human_attribute_name(:cost_point)
              th style="width: 25%;"
          tbody
            - @rewords.each do |reword|
              tr id="reword-#{reword.id}"
                td
                  - if reword.asin.present?
                    = link_to reword.name, "https://www.amazon.co.jp/s?k=#{reword.name}&__mk_ja_JP=カタカナ&ref=nb_sb_noss", target: :_blank
                  - else
                    = reword.name
                td.small= raw Rinku.auto_link(simple_format(h(reword.description), {}, sanitize: false, wrapper_tag: "div"))
                td.text-right
                  = "#{reword.cost_point.to_s(:delimited)} pt"
                td.text-center
                  = link_to "交換", '#', data: {toggle:"modal",target:"#exchangeModal-#{reword.id}"}, class: 'btn btn-info mx-2'
                  - if current_profile.admin?
                    = link_to edit_reword_path(reword), id: "edit_#{reword.id}" do
                      = fa_icon 'edit', class: 'icon_list m-1 my-2'
                    = link_to reword, method: :delete, remote: true, id: "delete_#{reword.id}",
                    data: { confirm: "「#{reword.name}」を削除します。よろしいですか？" }, class: "delete" do
                      = fa_icon 'trash', class: 'icon_list m-1 my-2'
                  
        div.exchangeModal
          = render 'exchange_modal', rewords: @rewords
      .card-footer
        - if current_profile.admin?
          = link_to '新規登録', new_reword_path, class: 'btn btn-info'

app/views/rewords/new.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.col-md-8.offset-md-2
  = render 'form'