config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  post '/home/guest_sign_in', to: 'static_pages#new_guest'
  devise_for :users
  resources :chores do
    resources :chore_records, only: [:new, :edit]
  end
  resources :chore_records, only: [:create, :update, :destroy]
  resources :profiles do
    member do
      post :select
    end
  end
  resources :rewords do
    member do
      post :exchange
    end
  end
end

app/models/chore.rb
class Chore < ApplicationRecord

  # -- [Association] --
  belongs_to :user
  has_many :chore_records, dependent: :destroy
  has_many :points

  # -- [validation] --
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 255 }
  validates :point, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :date_type, presence: true
  validates :date, presence: true, if: Proc.new { |c| c.date_type == Chore.date_types[:target] }
  validates :start_date, presence: true, if: Proc.new { |c| c.date_type == Chore.date_types[:range] }
  validates :end_date, presence: true, if: Proc.new { |c| c.date_type == Chore.date_types[:range] }
  validate :start_end_check, if: Proc.new { |c| c.date_type == Chore.date_types[:range] }
  validates :wday, presence: true, if: Proc.new { |c| c.date_type == Chore.date_types[:day_of_week] }
  validates :mday, presence: true, if: Proc.new { |c| c.date_type == Chore.date_types[:day_of_month] }

  def start_end_check
    if self.start_date && self.end_date
      errors.add(:end_date, "の日付を正しく記入して下さい。") unless self.start_date < self.end_date
    end
  end

  # -- [scope] --
  # 最新を取得
  scope :recent, -> { order(created_at: :desc)}

  # -- [enum] --
  enum date_types: {
    all_day: 0,
    target: 1,
    range: 2,
    day_of_week: 3,
    day_of_month: 4
  }
  enum day_names: {
    sunday: 0,
    monday: 1,
    tuesday: 2,
    wednesday: 3,
    thursday: 4,
    friday: 5
  }

  # 今日のステータスを取得
  def today_record_status
    self.chore_records.today.exists? ? I18n.t("status.complete") : ""
  end
  # 今日の作業者を取得
  def today_record_operator
    self.chore_records.today.joins(:profile).pluck(:name).join(",")
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :authenticate_user!         # ログインユーザーのみアクセス許可
  before_action :confirm_selected_profile   # プロフィール選択中のみアクセス許可
  before_action :set_chore, only: [:show, :edit, :update, :destroy]
  
  def index
    @chores = current_user.chores.recent.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @chore = Chore.new
  end

  def create
    @chore = current_user.chores.new(chore_params)
    if @chore.save
      flash[:success] = "「#{@chore.name}」のお手伝い情報を登録しました。"
      redirect_to chores_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chore.update_attributes(chore_params)
      flash[:success] = "「#{@chore.name}」のお手伝い情報を更新しました。"
      redirect_to @chore
    else
      render :edit
    end
  end

  def destroy
    @chore.destroy
    @chores = current_user.chores.recent.page(params[:page]).per(10)
    respond_to do |format|
      format.html { redirect_to chores_path }
      format.js
    end
  end

  private

  def chore_params
    params.require(:chore).permit(:name, :description,:point, :all_day, 
                                  :date_type, :date, :start_date, :end_date,
                                  :wday, :mday)
  end

  # 対象idのお手伝い情報を設定
  def set_chore
    @chore = current_user.chores.find(params[:id])
  end
end

app/helpers/chores_helper.rb
module ChoresHelper

  # 日程を編集して返す
  def format_date_type(chore)
    case chore.date_type
    when Chore.date_types[:all_day]
      Chore.date_types_i18n[Chore.date_types.key(chore.date_type)]
    when Chore.date_types[:target]
      I18n.l(chore.date)
    when Chore.date_types[:range]
      "#{I18n.l(chore.start_date)} 〜 #{I18n.l(chore.end_date)}"
    when Chore.date_types[:day_of_week]
      return "" unless chore.wday
      "毎週#{Chore.day_names_i18n[Chore.day_names.key(chore.wday)]}"
    when Chore.date_types[:day_of_month]
      chore.mday ? "毎月#{chore.mday}日" : ""
    end
  end
end

app/views/chores/_chores.html.slim
table.table.table-hover
  thead.thead-default
    tr
      th style="width: 30%;"= Chore.human_attribute_name(:name)
      th style="width: 30%;"= Chore.human_attribute_name(:date_type)
      th style="width: 20%;"= Chore.human_attribute_name(:point)
      th style="width: 20%;"
  tbody
    - chores.each do |chore|
      tr id="chore-#{chore.id}"
        td= link_to chore.name, chore
        td= format_date_type chore
        td.text-right
          = "#{chore.point.to_s(:delimited)} pt"
        td.text-right
          = link_to new_chore_chore_record_path(chore_id: chore.id), id: "new_#{chore.id}" do
            = fa_icon 'calendar-plus-o', class: 'icon_list mx-2'
          - if current_profile.admin?
            = link_to edit_chore_path(chore), id: "edit_#{chore.id}" do
              = fa_icon 'edit', class: 'icon_list mx-2'
            = link_to chore, method: :delete, remote: true, id: "delete_#{chore.id}",
            data: { confirm: "「#{chore.name}」を削除します。よろしいですか？" }, class: "delete" do
              = fa_icon 'trash', class: 'icon_list mx-2'
.mt-3.mx-3
  = paginate chores
  .mb-t.small.text-muted
    = page_entries_info chores

app/views/chores/_form.html.slim
= form_with model: @chore, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, required: true, maxlength: 30, class: 'form-control', id: 'chore_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 3, maxlength: 255, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :point
    .form-inline
      = f.number_field :point, required: true, min: 0, class: 'form-control', id: 'chore_point'
      label.ml-3 pt

  .form-group
    = f.label :date_type
    = f.select :date_type, Chore.date_types.map { |k, v| [t("enums.chore.date_types.#{k}"), v]}  \
    , {}, {class: 'selectpicker form-control', id: 'chore_date_type'}

  .form-group#fg_chore_date 
    = f.label :date
    = f.date_field  :date, class: "form-control"
    / .input-group.date#dtp_date data-target-input='nearest'
    /   = f.text_field :date, placeholder: "日付を選択", class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#dtp_date"}
    /   .input-group-append[data-target="#dtp_date" data-toggle="datetimepicker"]
    /     .input-group-text
    /       i.fa.fa-calendar

  .form-group#fg_chore_start_date
    = f.label :start_date
    = f.date_field :start_date, class: 'form-control', id: 'chore_start_date'
    / .input-group.date#dtp_start_date data-target-input='nearest'
    /   = f.text_field :start_date, placeholder: "日付を選択", class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#dtp_start_date"}
    /   .input-group-append[data-target="#dtp_start_date" data-toggle="datetimepicker"]
    /     .input-group-text
    /       i.fa.fa-calendar
  .form-group#fg_chore_end_date
    = f.label :end_date
    = f.date_field :end_date, class: 'form-control', id: 'chore_end_date'
    / .input-group.date#dtp_end_date data-target-input='nearest'
    /   = f.text_field :end_date, placeholder: "日付を選択", class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#dtp_end_date"}
    /   .input-group-append[data-target="#dtp_end_date" data-toggle="datetimepicker"]
    /     .input-group-text
    /       i.fa.fa-calendar

  .form-group#fg_chore_wday
    = f.label :wday
    = f.select :wday, Chore.day_names.map { |k, v| [t("enums.chore.day_names.#{k}"), v]} \
      , {include_blank: true}, {class: 'form-control col-md-9', id: 'wday'}
  
  .form-group#fg_chore_mday
    = f.label :mday
    .form-inline
      = f.number_field :mday, class: 'form-control', min: 1, max: 31, id: 'chore_mday'
      label.ml-3 日
  
  = f.submit nil, class: 'btn btn-info btn-block'

app/views/chores/destroy.js.erb
$(".chores").html("<%= escape_javascript(render 'chores', chores: @chores) %>");
<%# var msg = document.createElement('p'); %>
<%# msg.innerText = '削除しました。'; %>
<%# document.querySelector('table').insertAdjacentElement('beforebegin', msg) %>

app/views/chores/edit.html.slim
- provide(:title, "お手伝い情報 編集")

h1 お手伝い情報 編集

.col-md-8.offset-md-2
  = render 'form'

app/views/chores/index.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.card
  .card-header お手伝いリスト
  .card-body.chores.pt-0.px-2
      = render 'chores', chores: @chores
  .card-footer
    - if current_profile.admin?
      = link_to '新規登録', new_chore_path, class: 'btn btn-info'

app/views/chores/show.html.slim
- provide(:title, t('.title'))
h1= t('.title')

.row
  .col-md-5
    .card
      .card-header お手伝い詳細情報
      .card-body
        table.table.table-hover
          tbody
            tr
              th style="width: 35%;"= Chore.human_attribute_name(:name)
              td style="width: 65%;"= @chore.name
            tr
              th= Chore.human_attribute_name(:description)
              td= raw Rinku.auto_link(simple_format(h(@chore.description), {}, sanitize: false, wrapper_tag: "div"))
            tr
              th= Chore.human_attribute_name(:point)
              td= "#{@chore.point.to_s(:delimited)} pt"
            tr
              th= Chore.human_attribute_name(:date_type)
              td= format_date_type @chore
            tr
              th= Chore.human_attribute_name(:created_at)
              td.small= l @chore.created_at, format: :long
            tr
              th= Chore.human_attribute_name(:updated_at)
              td.small= l @chore.updated_at, format: :long
      .card-footer
        - if current_profile.admin?
          = link_to '編集', edit_chore_path, class: 'btn btn-info mr-3'
          = link_to '削除', @chore, method: :delete, \
          data: { confirm: "お手伝い「#{@chore.name}」を削除します。よろしいですか？" }, \
          class: 'btn btn-danger mr-3'

  .my-3
  .col-md-7
    .card.
      .card-header お手伝い記録履歴
      .card-body.card-body_h500
        table.table.table-hover.chore_records
          thead.thead-default
            tr
              th style="width: 20%;"= t(".operater")
              th style="width: 30%;"= ChoreRecord.human_attribute_name(:actual_date)
              th style="width: 30%;"= ChoreRecord.human_attribute_name(:comment)
              th style="width: 20%;"
          tbody
            - @chore.chore_records.recent.each do |record|
              tr
                td= record.profile.name
                td.center.small
                  = l(record.actual_date, format: :long)
                td.small= raw Rinku.auto_link(simple_format(h(record.comment), {}, sanitize: false, wrapper_tag: "div"))
                td.text-center
                  = link_to edit_chore_chore_record_path(@chore,record) do
                    = fa_icon 'edit', class: 'icon_list mr-1'
                  = link_to record, method: :delete, \
                  data: { confirm: "#{l(record.actual_date, format: :long)}の記録を削除します。よろしいですか？" } do
                    = fa_icon 'trash', class: 'icon_list'
      .card-footer
        = link_to 'お手伝い記録', new_chore_chore_record_path(@chore.id), class: 'btn btn-info mr-3'